services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    networks:
      - java_app
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
    restart: always

  expenses-app:
    build:
      context: .
    container_name: expensesapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    networks: 
      - java_app
    depends_on:
      mysql: 
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
    restart: always
   
networks:
  java_app:
    name: java_app
