name: CICD

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["push to dockerhub"] # Must exactly match the name of your first workflow
  #   types:
  #     - completed
  #   branches: [test]



jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    runs-on: self-hosted
    steps:
      - name: CODE CHECKOUT   
        uses: actions/checkout@v5

      - name: docker compose
        run: docker compose up -d --force-recreate
