name: deploying the application

on:
  push:
        branches: [test]
  workflow_run:
    workflows: [push to dockerhub]   # Must exactly match the first workflow's name
    types:
      - completed


jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        runs-on: self-hosted
        steps:
            - name: CODE CHECKOUT   
              uses: actions/checkout@v5

            - name: Pull latest image
              run: docker compose pull

            - name: docker compose
              run: docker compose up -d --force-recreate
