name: deploying the application

on:
    push:
        branches: [test]
    workflow_dispatch:


jobs:
    deploy:
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        runs-on: self-hosted
        steps:
            - name: CODE CHECKOUT   
              uses: actions/checkout@v5

            - name: Pull latest image
              run: docker compose pull

            - name: docker compose
              run: docker compose up -d --force-recreate